# -*- coding: utf-8 -*-
import requests
# Form implementation generated from reading ui file 'SolutionDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QPixmap
from PyQt5.QtWidgets import QDialog, QFileDialog
from myreqeust.HttpTool import HttpTool
from myreqeust.PathConstant import PathConstant


class SolutionDialog(QDialog):
    def __init__(self,questionId):
        super().__init__()
        self.question_id=questionId
        self.setupUi()
        self.setWindowModality(Qt.ApplicationModal)

    def setupUi(self,):
        self.setObjectName("Dialog")
        self.resize(724, 702)
        self.buttonBox = QtWidgets.QDialogButtonBox(self)
        self.buttonBox.setGeometry(QtCore.QRect(340, 640, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(90, 60, 72, 15))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self)
        self.comboBox.setGeometry(QtCore.QRect(190, 60, 87, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(self)
        self.label_2.setGeometry(QtCore.QRect(90, 150, 72, 15))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self)
        self.pushButton.clicked.connect(self.uploadImage)
        self.pushButton.setGeometry(QtCore.QRect(200, 150, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.image_lable = QtWidgets.QLabel(self)
        self.image_lable.setGeometry(QtCore.QRect(50, 250, 571, 331))
        self.image_lable.setObjectName("image_lable")

        self.retranslateUi(self)
        self.buttonBox.accepted.connect(self.add_solution) # type: ignore
        self.buttonBox.rejected.connect(self.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "答案"))
        self.comboBox.setItemText(0, _translate("Dialog", "0"))
        self.comboBox.setItemText(1, _translate("Dialog", "A"))
        self.comboBox.setItemText(2, _translate("Dialog", "B"))
        self.comboBox.setItemText(3, _translate("Dialog", "C"))
        self.comboBox.setItemText(4, _translate("Dialog", "D"))
        self.label_2.setText(_translate("Dialog", "图片"))
        self.pushButton.setText(_translate("Dialog", "PushButton"))
        self.image_lable.setText(_translate("Dialog", "TextLabel"))

    def add_solution(self):
        data = {}
        data["qustionId"] = self.question_id
        data["type"] = self.comboBox.currentText()
        if self.image_src:
            data["imageSrc"]=self.image_src
            HttpTool.post(PathConstant.ADD_SOLUTION, data)
        self.accept()

    def uploadImage(self):
        options = QFileDialog.Options()
        options |= QFileDialog.ReadOnly
        file_path, _ = QFileDialog.getOpenFileName(self, "Select Image", "", "Images (*.png *.jpg *.jpeg *.gif)",
                                                   options=options)
        if file_path:
            with open(file_path, 'rb') as image_file:
                files = {'file': (file_path, image_file)}
                response = requests.post(PathConstant.UPLOAD_IMAGE, files=files)

                if response.status_code == 200:
                    self.image_src=response.json()["msg"]
                    self.display_online_image(self.image_src)
                    print("Image uploaded successfully")
                else:
                    print("Image upload failed. Status code:", response.status_code)
# 显示在线图片
    def display_online_image(self, image_url):
        response = requests.get(image_url)
        if response.status_code == 200:
            image_data = response.content
            pixmap = QPixmap()
            pixmap.loadFromData(image_data)
            self.image_lable.setPixmap(pixmap)
            self.image_lable.setScaledContents(True)  # 自动缩放图片以适应标签大小
        else:
            self.image_label.setText("Failed to load image")