# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(697, 619)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 40, 31, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(220, 40, 81, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(70, 40, 87, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(190, 40, 72, 15))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(330, 40, 72, 15))
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(380, 40, 113, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(520, 40, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.treeWidget = QtWidgets.QTreeWidget(Form)
        self.treeWidget.setGeometry(QtCore.QRect(110, 200, 391, 192))
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "章"))
        self.comboBox.setItemText(0, _translate("Form", "第一章"))
        self.comboBox.setItemText(1, _translate("Form", "第二章"))
        self.label_2.setText(_translate("Form", "节"))
        self.label_3.setText(_translate("Form", "名称"))
        self.pushButton.setText(_translate("Form", "搜索"))
        self.treeWidget.headerItem().setText(0, _translate("Form", "id"))
        self.treeWidget.headerItem().setText(1, _translate("Form", "a"))
        self.treeWidget.headerItem().setText(2, _translate("Form", "b"))
        self.treeWidget.headerItem().setText(3, _translate("Form", "c"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("Form", "1"))
        self.treeWidget.topLevelItem(0).setText(1, _translate("Form", "2"))
        self.treeWidget.topLevelItem(0).setText(2, _translate("Form", "3"))
        self.treeWidget.topLevelItem(0).setText(3, _translate("Form", "4"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("Form", "4"))
        self.treeWidget.topLevelItem(0).child(0).setText(1, _translate("Form", "5"))
        self.treeWidget.topLevelItem(0).child(0).setText(2, _translate("Form", "6"))
        self.treeWidget.topLevelItem(0).child(0).setText(3, _translate("Form", "7"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
