# -*- coding: utf-8 -*-
import sys

# Form implementation generated from reading ui file 'Sectionself.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QApplication,  QDialog

from myreqeust.PathConstant import PathConstant
from myreqeust.RequestTools import RequestTools

class SectionDialog(QDialog):
    def __init__(self,pid,chapter_id):
        super().__init__()
        self.pid=pid
        self.chapter_id=chapter_id
        self.setupUi()
        self.setWindowModality(Qt.ApplicationModal)
    def setupUi(self):

        self.setObjectName("小节form")
        self.resize(675, 546)
        self.buttonBox = QtWidgets.QDialogButtonBox(self)
        self.buttonBox.setGeometry(QtCore.QRect(320, 480, 341, 41))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(90, 60, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.nameLineEdit = QtWidgets.QLineEdit(self)
        self.nameLineEdit.setGeometry(QtCore.QRect(190, 60, 191, 31))
        self.nameLineEdit.setMaxLength(50)
        self.nameLineEdit.setObjectName("nameLineEdit")

        self.label_2 = QtWidgets.QLabel(self)
        self.label_2.setGeometry(QtCore.QRect(90, 120, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.sortLineEdit = QtWidgets.QLineEdit(self)
        self.sortLineEdit.setGeometry(QtCore.QRect(182, 130, 191, 31))
        self.sortLineEdit.setMaxLength(2)
        self.sortLineEdit.setObjectName("sortLineEdit")
        self.label_3 = QtWidgets.QLabel(self)
        self.label_3.setGeometry(QtCore.QRect(30, 180, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.importanceLineEdit = QtWidgets.QLineEdit(self)
        self.importanceLineEdit.setGeometry(QtCore.QRect(190, 190, 191, 31))
        self.importanceLineEdit.setMaxLength(2)
        self.importanceLineEdit.setObjectName("importanceLineEdit")
        self.label_4 = QtWidgets.QLabel(self)
        self.label_4.setGeometry(QtCore.QRect(30, 250, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.difficlutyLineEdit = QtWidgets.QLineEdit(self)
        self.difficlutyLineEdit.setGeometry(QtCore.QRect(190, 260, 191, 31))
        self.difficlutyLineEdit.setMaxLength(2)
        self.difficlutyLineEdit.setObjectName("difficlutyLineEdit")

        self.retranslateUi()
        self.buttonBox.accepted.connect(self.addSection) # type: ignore
        self.buttonBox.rejected.connect(self.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("self", "self"))
        self.label.setText(_translate("self", "名称"))
        self.label_2.setText(_translate("self", "sort"))
        self.label_3.setText(_translate("self", "重要程度"))
        self.label_4.setText(_translate("self", "困难程度"))




    # 新增知识点
    def addSection(self):
        print(123)
        sort=int(self.sortLineEdit.text())
        importance=int(self.importanceLineEdit.text())
        difficluty=int(self.difficlutyLineEdit.text())
        name=self.nameLineEdit.text()
        data={}
        data["name"]=name
        data["sort"]=sort
        data["chapterId"]=self.chapter_id
        data["importance"]=importance
        data["difficulty"]=difficluty
        data["pid"]=self.pid
        RequestTools.post_method(PathConstant.ADD_SECTION,data)
        self.accept()
