# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StepDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QDialog

from myreqeust.PathConstant import PathConstant
from myreqeust.RequestTools import RequestTools


class StepDialog(QDialog):
    def __init__(self,section_id):
        super().__init__()
        self.section_id=section_id
        self.setupUi()
        self.setWindowModality(Qt.ApplicationModal)

    def setupUi(self):
        self.setObjectName("Dialog")
        self.resize(471, 401)
        self.buttonBox = QtWidgets.QDialogButtonBox(self)
        self.buttonBox.setGeometry(QtCore.QRect(120, 350, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(80, 90, 241, 121))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.sort_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.sort_lineEdit.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.sort_lineEdit, 1, 1, 1, 1)
        self.name_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.name_lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.name_lineEdit, 0, 1, 1, 1)

        self.retranslateUi(self)
        self.buttonBox.accepted.connect(self.accept) # type: ignore
        self.buttonBox.rejected.connect(self.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "排序"))
        self.label_3.setText(_translate("Dialog", "名称"))

    def addStep(self):
        data = {}
        data["name"] = self.name_lineEdit.text()
        data["sort"] = self.sort_lineEdit.text()
        data["sectionId"] = self.section_id
        RequestTools.post_method(PathConstant.ADD_STEP, data)
        self.accept()