# -*- coding: utf-8 -*-
import requests
# Form implementation generated from reading ui file 'ImageDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QPixmap
from PyQt5.QtWidgets import QDialog, QFileDialog

from myreqeust.HttpTool import HttpTool
from myreqeust.PathConstant import PathConstant
from myreqeust.RequestTools import RequestTools


class StepDialog(QDialog):
    def __init__(self,section_id):
        super().__init__()
        self.section_id=section_id
        self.setupUi()
        self.setWindowModality(Qt.ApplicationModal)

    def setupUi(self):
        self.setObjectName("图片")
        self.resize(500, 604)
        self.buttonBox = QtWidgets.QDialogButtonBox(self)
        self.buttonBox.setGeometry(QtCore.QRect(120, 540, 341, 31))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.name_label = QtWidgets.QLabel(self)
        self.name_label.setGeometry(QtCore.QRect(50, 50, 72, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.name_label.setFont(font)
        self.name_label.setObjectName("name_label")
        self.name_lineEdit = QtWidgets.QLineEdit(self)
        self.name_lineEdit.setGeometry(QtCore.QRect(190, 50, 113, 21))
        self.name_lineEdit.setObjectName("name_lineEdit")
        self.picture_label = QtWidgets.QLabel(self)
        self.picture_label.setGeometry(QtCore.QRect(60, 120, 72, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.picture_label.setFont(font)
        self.picture_label.setObjectName("picture_label")
        self.pushButton = QtWidgets.QPushButton(self)
        self.pushButton.setGeometry(QtCore.QRect(190, 130, 93, 28))
        self.pushButton.setObjectName("新增图片")
        self.pushButton.clicked.connect(self.uploadImage)
        self.sort_label = QtWidgets.QLabel(self)
        self.sort_label.setGeometry(QtCore.QRect(60, 190, 72, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.sort_label.setFont(font)
        self.sort_label.setObjectName("sort_label")
        self.sort_lineEdit = QtWidgets.QLineEdit(self)
        self.sort_lineEdit.setGeometry(QtCore.QRect(180, 210, 113, 21))
        self.sort_lineEdit.setObjectName("sort_lineEdit")
        self.image_label = QtWidgets.QLabel(self)
        self.image_label.setGeometry(QtCore.QRect(60, 280, 291, 171))
        self.image_label.setObjectName("image_label")

        self.retranslateUi(self)
        self.buttonBox.accepted.connect(self.add_step) # type: ignore
        self.buttonBox.rejected.connect(self.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.name_label.setText(_translate("Dialog", "名称"))
        self.picture_label.setText(_translate("Dialog", "图片"))
        self.pushButton.setText(_translate("Dialog", "PushButton"))
        self.sort_label.setText(_translate("Dialog", "sort"))
        self.image_label.setText(_translate("Dialog", "TextLabel"))

# 显示在线图片
    def display_online_image(self, image_url):
        response = requests.get(image_url)
        if response.status_code == 200:
            image_data = response.content
            pixmap = QPixmap()
            pixmap.loadFromData(image_data)
            self.image_label.setPixmap(pixmap)
            self.image_label.setScaledContents(True)  # 自动缩放图片以适应标签大小
        else:
            self.image_label.setText("Failed to load image")

    def uploadImage(self):
        options = QFileDialog.Options()
        options |= QFileDialog.ReadOnly
        file_path, _ = QFileDialog.getOpenFileName(self, "Select Image", "", "Images (*.png *.jpg *.jpeg *.gif)",
                                                   options=options)
        if file_path:
            with open(file_path, 'rb') as image_file:
                files = {'file': (file_path, image_file)}
                response = requests.post(PathConstant.UPLOAD_IMAGE, files=files)

                if response.status_code == 200:
                    self.image_src=response.json()["msg"]
                    self.display_online_image(self.image_src)
                    print("Image uploaded successfully")
                else:
                    print("Image upload failed. Status code:", response.status_code)

    def add_step(self):
        data = {}
        data["name"] = self.name_lineEdit.text()
        data["sort"] = self.sort_lineEdit.text()
        data["sectionId"] = self.section_id
        if self.image_src:
            data["imageSrc"]=self.image_src
            HttpTool.post(PathConstant.ADD_STEP, data)
        self.accept()